all:
	javac graphNode.java
	javac graphNodeList.java
	javac graph.java
	javac driverGraph.java
	javac TaxiService.java
	javac checker.java

run:
	java checker

debugGraph:
	java driverGraph	

clean:
	rm *.class	